In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("_classes.csv")
df

,filename,Unlabeled,age related macular degeneration,cataract,diabetes,glaucoma,hypertension,normal
0,image190_png.rf.d862e83fc7aa54f471de7c5a3c4882...,0,0,0,0,1,0,0
1,3416_left_jpg.rf.d907909022677bcd8843b15fa4fb8...,0,0,0,0,0,0,1
2,_12_7315004_jpg.rf.d917e101f464914706d8c39f100...,0,0,0,0,0,1,0
3,1869_left_jpg.rf.da408b295014fa98a8f90297afafb...,0,1,0,0,0,0,0
4,1043_right_jpg.rf.d9adccaa1c2e7dafa0c648b83b9b...,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...
2344,2176_left_jpg.rf.864f4c0a8b5f5b294222993f0849d...,0,0,1,0,0,0,0
2345,image93_png.rf.878a3d2beceda73e5ae99eefae404e3...,0,0,0,0,1,0,0
2346,615_right_jpg.rf.879857a7ff0a33eec20050bc6c7b3...,0,1,0,0,0,0,0
2347,4044_left_jpg.rf.86d47bf869575e941c51311d2c621...,0,0,0,1,0,0,0
2348,1492_right_jpg.rf.87ab5ff0292b8502af50bb9050ef...,0,0,0,0,1,0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2349 entries, 0 to 2348
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   filename                           2349 non-null   object
 1    Unlabeled                         2349 non-null   int64
 2    age related macular degeneration  2349 non-null   int64
 3    cataract                          2349 non-null   int64
 4    diabetes                          2349 non-null   int64
 5    glaucoma                          2349 non-null   int64
 6    hypertension                      2349 non-null   int64
 7    normal                            2349 non-null   int64
dtypes: int64(7), object(1)
memory usage: 146.9+ KB

In [5]:
df.columns

Index(['filename', ' Unlabeled', ' age related macular degeneration',
       ' cataract', ' diabetes', ' glaucoma', ' hypertension', ' normal'],
      dtype='object')

## Updated cell
### Changing Columns name

In [6]:
df.columns = df.columns.map(lambda x : x.lstrip())

df.rename(columns={'age related macular degeneration': 'age_related_macular_degeneration'}, inplace=True)

In [7]:
df.columns

Index(['filename', 'Unlabeled', 'age_related_macular_degeneration', 'cataract',
       'diabetes', 'glaucoma', 'hypertension', 'normal'],
      dtype='object')

In [8]:
l1 = (df[df['Unlabeled'] == 1].loc[:, 'filename'])

In [9]:
unlabeled_files = l1.values.tolist()

In [10]:
condition = df['Unlabeled'] == 1

In [11]:
df3 = df[~condition]

In [12]:
df3

,filename,Unlabeled,age_related_macular_degeneration,cataract,diabetes,glaucoma,hypertension,normal
0,image190_png.rf.d862e83fc7aa54f471de7c5a3c4882...,0,0,0,0,1,0,0
1,3416_left_jpg.rf.d907909022677bcd8843b15fa4fb8...,0,0,0,0,0,0,1
2,_12_7315004_jpg.rf.d917e101f464914706d8c39f100...,0,0,0,0,0,1,0
3,1869_left_jpg.rf.da408b295014fa98a8f90297afafb...,0,1,0,0,0,0,0
4,1043_right_jpg.rf.d9adccaa1c2e7dafa0c648b83b9b...,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...
2344,2176_left_jpg.rf.864f4c0a8b5f5b294222993f0849d...,0,0,1,0,0,0,0
2345,image93_png.rf.878a3d2beceda73e5ae99eefae404e3...,0,0,0,0,1,0,0
2346,615_right_jpg.rf.879857a7ff0a33eec20050bc6c7b3...,0,1,0,0,0,0,0
2347,4044_left_jpg.rf.86d47bf869575e941c51311d2c621...,0,0,0,1,0,0,0
2348,1492_right_jpg.rf.87ab5ff0292b8502af50bb9050ef...,0,0,0,0,1,0,0

In [13]:
df3.drop(columns='Unlabeled', inplace= True)

In [14]:
df3

,filename,age_related_macular_degeneration,cataract,diabetes,glaucoma,hypertension,normal
0,image190_png.rf.d862e83fc7aa54f471de7c5a3c4882...,0,0,0,1,0,0
1,3416_left_jpg.rf.d907909022677bcd8843b15fa4fb8...,0,0,0,0,0,1
2,_12_7315004_jpg.rf.d917e101f464914706d8c39f100...,0,0,0,0,1,0
3,1869_left_jpg.rf.da408b295014fa98a8f90297afafb...,1,0,0,0,0,0
4,1043_right_jpg.rf.d9adccaa1c2e7dafa0c648b83b9b...,1,0,0,0,0,0
...,...,...,...,...,...,...,...
2344,2176_left_jpg.rf.864f4c0a8b5f5b294222993f0849d...,0,1,0,0,0,0
2345,image93_png.rf.878a3d2beceda73e5ae99eefae404e3...,0,0,0,1,0,0
2346,615_right_jpg.rf.879857a7ff0a33eec20050bc6c7b3...,1,0,0,0,0,0
2347,4044_left_jpg.rf.86d47bf869575e941c51311d2c621...,0,0,1,0,0,0
2348,1492_right_jpg.rf.87ab5ff0292b8502af50bb9050ef...,0,0,0,1,0,0

In [15]:
df3.reset_index(drop=True)

,filename,age_related_macular_degeneration,cataract,diabetes,glaucoma,hypertension,normal
0,image190_png.rf.d862e83fc7aa54f471de7c5a3c4882...,0,0,0,1,0,0
1,3416_left_jpg.rf.d907909022677bcd8843b15fa4fb8...,0,0,0,0,0,1
2,_12_7315004_jpg.rf.d917e101f464914706d8c39f100...,0,0,0,0,1,0
3,1869_left_jpg.rf.da408b295014fa98a8f90297afafb...,1,0,0,0,0,0
4,1043_right_jpg.rf.d9adccaa1c2e7dafa0c648b83b9b...,1,0,0,0,0,0
...,...,...,...,...,...,...,...
2330,2176_left_jpg.rf.864f4c0a8b5f5b294222993f0849d...,0,1,0,0,0,0
2331,image93_png.rf.878a3d2beceda73e5ae99eefae404e3...,0,0,0,1,0,0
2332,615_right_jpg.rf.879857a7ff0a33eec20050bc6c7b3...,1,0,0,0,0,0
2333,4044_left_jpg.rf.86d47bf869575e941c51311d2c621...,0,0,1,0,0,0
2334,1492_right_jpg.rf.87ab5ff0292b8502af50bb9050ef...,0,0,0,1,0,0

In [16]:
df3['sum'] = df3.sum(axis=1).tolist()

In [17]:
multilabel_files =  df3[df3['sum']>1]['filename'].tolist()

In [18]:
for i in unlabeled_files:
    multilabel_files.append(i)

In [19]:
len(multilabel_files)

67

## Deleting unlabeled and multilabeled Images

In [20]:
import os

# Define the directory where your image files are located
directory = 'input'

# Define a list of image filenames you want to delete
image_files_to_delete = multilabel_files

# Iterate over the files in the directory
for filename in os.listdir(directory):
    file_path = os.path.join(directory, filename)

    # Check if the file is in the list of files to delete
    if filename in image_files_to_delete:
        # Delete the file
        os.remove(file_path)
        print(f"Deleted: {file_path}")

Deleted: input\1024_right_jpg.rf.54dd9a6771464e4087251e9ed3aefd12.jpg
Deleted: input\1056_right_jpg.rf.eb93a9afd992f0a1b62af599376b0103.jpg
Deleted: input\1059_right_jpg.rf.0ddf5d5996a8719f29f453b04d29376d.jpg
Deleted: input\1084_right_jpg.rf.b5f3caa510e3ee4c73dc7488db02e201.jpg
Deleted: input\1102_right_jpg.rf.b889daa7c0d8eee50c7a42ae67f87b00.jpg
Deleted: input\1136_left_jpg.rf.83361f26462d088aaf973628f327482d.jpg
Deleted: input\1144_right_jpg.rf.fd1b9528eecafd006012f95bf3355213.jpg
Deleted: input\1146_right_jpg.rf.6abd9926c26d340a739c10c2cea2fe04.jpg
Deleted: input\1154_right_jpg.rf.883eb7e0fa5645e6a82fafc0f50af7d4.jpg
Deleted: input\1230_right_jpg.rf.57280291defe4afb5d3bdfd0b064664f.jpg
Deleted: input\1251_right_jpg.rf.92c6711883477631c97fe630e6aed442.jpg
Deleted: input\1263_right_jpg.rf.ba63199dddc466176e4045e6a685cf8d.jpg
Deleted: input\127_left_jpg.rf.518211d29ac138b2d4e653c054060aaa.jpg
Deleted: input\1280_left_jpg.rf.211a9d24c11be0feb1eb94d333731645.jpg
Deleted: input\1290_left_jpg.rf.bdc0d5ff6a859a5e5c720940ad5bfba7.jpg
Deleted: input\1309_left_jpg.rf.2da1eb287f8ad5759371af44681a6757.jpg
Deleted: input\1309_right_jpg.rf.52e8de0b2c0dbed6333908894493b787.jpg
Deleted: input\1314_left_jpg.rf.d5d440198b45d8cc0f749d4731d12be1.jpg
Deleted: input\1314_right_jpg.rf.e32668dbe27625926665e46f6c5a857d.jpg
Deleted: input\1377_right_jpg.rf.d2e5b19ffea060af48bc7f5bcef01969.jpg
Deleted: input\1434_right_jpg.rf.ad6fa5951fc48e5b6720c1f5daa09a35.jpg
Deleted: input\1458_left_jpg.rf.f1774480f5a479aa18382c82311b985c.jpg
Deleted: input\1458_right_jpg.rf.432033f4d04a3b7385d027a9e81b09c8.jpg
Deleted: input\176_left_jpg.rf.26a902985e9da635bdd9bcb3611d2276.jpg
Deleted: input\176_right_jpg.rf.4487dada3df4c1f4695f30a13492c0ac.jpg
Deleted: input\1881_left_jpg.rf.a4211d7fb831326fa896462fdc774c99.jpg
Deleted: input\1942_right_jpg.rf.72145b6bb49ba4d21a70134574d5276e.jpg
Deleted: input\2010_left_jpg.rf.32f6954e273a8c735cc5762c4a3c057b.jpg
Deleted: input\2041_left_jpg.rf.7d60526e71617f3100005b5f922388a0.jpg
Deleted: input\2052_left_jpg.rf.a55c75ac86f4f7640d2e623433b2c0d6.jpg
Deleted: input\2052_right_jpg.rf.0b3e3becd310457386fc8dc6fa77bacd.jpg
Deleted: input\2064_left_jpg.rf.9ca6232fcf45850fa8d404d0c45b22a7.jpg
Deleted: input\2064_right_jpg.rf.b68004dc2845bc2acd949ae0aa1becca.jpg
Deleted: input\212_left_jpg.rf.0e24c68ccea9671de176ca00b14160a3.jpg
Deleted: input\2164_left_jpg.rf.276cd5a21dc6eeb8fe170b037651074b.jpg
Deleted: input\247_right_jpg.rf.8abe3c818e7f9cfb11bbb16ef5d61bfd.jpg
Deleted: input\2561_right_jpg.rf.b30eeac5df5e8d5a4950c5fea98d3662.jpg
Deleted: input\270_left_jpg.rf.c0772899fcde8ce7f68d1378a7bb7cc7.jpg
Deleted: input\3091_right_jpg.rf.919858b47eefb477871715ceac5b0a46.jpg
Deleted: input\365_left_jpg.rf.387ec0d0e9a58da65c4ba230f67b282f.jpg
Deleted: input\365_right_jpg.rf.55400e42924c1599bcaa403d70a4b070.jpg
Deleted: input\3966_left_jpg.rf.a6d24c35f5e5b2b43c6466dd1ab6bc43.jpg
Deleted: input\3979_right_jpg.rf.4c94bfdd80a39c78de5e147835190899.jpg
Deleted: input\3981_left_jpg.rf.356b4c3933ea3e31ed7f36a54aea2452.jpg
Deleted: input\3986_left_jpg.rf.3240e7ca7f4982033c313f6df2e5070b.jpg
Deleted: input\4012_left_jpg.rf.a3471f17b40e2bbfa1fd33496f84b06a.jpg
Deleted: input\4012_right_jpg.rf.e4499032d5d11b646d864cbf18e0558e.jpg
Deleted: input\4037_right_jpg.rf.fe3aed1ed6e40ee7357697871dfc0dd0.jpg
Deleted: input\4072_right_jpg.rf.437c078bb4bb9a50fcc35cb61e3cd1bb.jpg
Deleted: input\4077_left_jpg.rf.0eb8f366108c54f01fdb7e447f198d19.jpg
Deleted: input\4088_right_jpg.rf.6b2534182a1c71d5252dea87588b1421.jpg
Deleted: input\4090_right_jpg.rf.a40483185e27d6d3cfae94097bf32263.jpg
Deleted: input\4199_left_jpg.rf.67ec93205a641ed1fb1b360dff1365f4.jpg
Deleted: input\4214_left_jpg.rf.3b85516da971cb03ed2b16e7e0d9f6b0.jpg
Deleted: input\4235_right_jpg.rf.f61082b1c397051a2285694f68a2d819.jpg
Deleted: input\4336_left_jpg.rf.1dd1214dcc08c044f82dec6ad770f265.jpg
Deleted: input\625_left_jpg.rf.1084a8c2778b3e19d5528fe6f87107c5.jpg
Deleted: input\71_right_jpg.rf.689f27fffa66117f1f2a7192adf740cf.jpg
Deleted: input\754_right_jpg.rf.1be5344a4494604fc554136a5cef3a8c.jpg
Deleted: input\934_right_jpg.rf.e401dbe749b34be377c308bb7d3fec9e.jpg
Deleted: input\970_left_jpg.rf.c2404bcac3bc6bf6e51f68c72ee62aa4.jpg
Deleted: input\image37_png.rf.a96328e3d11e76125d4a22b2dc96efdd.jpg
Deleted: input\image50_png.rf.0c861d3335addf8b9e3fa7217927dea1.jpg
Deleted: input\image79_png.rf.2dc651d632b45cf44d83bccf9af1a348.jpg
Deleted: input\_14_4848982_jpg.rf.e14767a2abdd8aaccecab9f2f4685037.jpg
Deleted: input\_15_774406_jpg.rf.339c8dff31eeaba1ce2a23158e11a2aa.jpg
Deleted: input\_7_7861119_jpg.rf.8c491bcdb8d22761c7dea04de69aadb7.jpg

In [21]:
indices = df3[df3['sum']>1].index

In [22]:
df3.drop(indices, axis=0, inplace=True)

In [23]:
df3.shape

(2282, 8)

In [24]:
df3.drop('sum' , axis=1, inplace=True)

In [25]:
dictionary = {1 : 'age_related_macular_degeneration', 2 : 'cataract',3 : 'diabetes',4 : 'glaucoma',5 : 'hypertension',6 : 'normal'}

In [26]:
df3['cataract'] = df3['cataract'].replace({1 : 2})

In [27]:
df3['diabetes'] = df3['diabetes'].replace({ 1 : 3})

In [28]:
df3['glaucoma'] = df3['glaucoma'].replace({ 1 : 4})

In [29]:
df3['hypertension'] = df3['hypertension'].replace( {1 : 5})

In [30]:
df3['normal'] = df3['normal'].replace({1 : 6})

In [31]:
df3['sum'] = df3.sum(axis=1, numeric_only= True)

In [32]:
df3

,filename,age_related_macular_degeneration,cataract,diabetes,glaucoma,hypertension,normal,sum
0,image190_png.rf.d862e83fc7aa54f471de7c5a3c4882...,0,0,0,4,0,0,4
1,3416_left_jpg.rf.d907909022677bcd8843b15fa4fb8...,0,0,0,0,0,6,6
2,_12_7315004_jpg.rf.d917e101f464914706d8c39f100...,0,0,0,0,5,0,5
3,1869_left_jpg.rf.da408b295014fa98a8f90297afafb...,1,0,0,0,0,0,1
4,1043_right_jpg.rf.d9adccaa1c2e7dafa0c648b83b9b...,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...
2344,2176_left_jpg.rf.864f4c0a8b5f5b294222993f0849d...,0,2,0,0,0,0,2
2345,image93_png.rf.878a3d2beceda73e5ae99eefae404e3...,0,0,0,4,0,0,4
2346,615_right_jpg.rf.879857a7ff0a33eec20050bc6c7b3...,1,0,0,0,0,0,1
2347,4044_left_jpg.rf.86d47bf869575e941c51311d2c621...,0,0,3,0,0,0,3
2348,1492_right_jpg.rf.87ab5ff0292b8502af50bb9050ef...,0,0,0,4,0,0,4

In [33]:
df4 = df3.loc[:, ['filename', 'sum']]

In [34]:
df4['sum'].replace(dictionary, inplace= True)

In [35]:
df4['sum'].value_counts()

cataract                            395
normal                              394
age_related_macular_degeneration    387
glaucoma                            376
hypertension                        371
diabetes                            359
Name: sum, dtype: int64

In [36]:
df4.rename(columns={'sum':'label'}, inplace=True)

In [37]:
df4

,filename,label
0,image190_png.rf.d862e83fc7aa54f471de7c5a3c4882...,glaucoma
1,3416_left_jpg.rf.d907909022677bcd8843b15fa4fb8...,normal
2,_12_7315004_jpg.rf.d917e101f464914706d8c39f100...,hypertension
3,1869_left_jpg.rf.da408b295014fa98a8f90297afafb...,age_related_macular_degeneration
4,1043_right_jpg.rf.d9adccaa1c2e7dafa0c648b83b9b...,age_related_macular_degeneration
...,...,...
2344,2176_left_jpg.rf.864f4c0a8b5f5b294222993f0849d...,cataract
2345,image93_png.rf.878a3d2beceda73e5ae99eefae404e3...,glaucoma
2346,615_right_jpg.rf.879857a7ff0a33eec20050bc6c7b3...,age_related_macular_degeneration
2347,4044_left_jpg.rf.86d47bf869575e941c51311d2c621...,diabetes
2348,1492_right_jpg.rf.87ab5ff0292b8502af50bb9050ef...,glaucoma

In [38]:
df4.to_csv('file_to_label1.csv', index= False)

In [39]:
df5 = df4.set_index('filename', drop=True)

In [40]:
df5

                                                                               label
filename
image190_png.rf.d862e83fc7aa54f471de7c5a3c48824...                          glaucoma
3416_left_jpg.rf.d907909022677bcd8843b15fa4fb89...                            normal
_12_7315004_jpg.rf.d917e101f464914706d8c39f1004...                      hypertension
1869_left_jpg.rf.da408b295014fa98a8f90297afafb0...  age_related_macular_degeneration
1043_right_jpg.rf.d9adccaa1c2e7dafa0c648b83b9b4...  age_related_macular_degeneration
...                                                                              ...
2176_left_jpg.rf.864f4c0a8b5f5b294222993f0849d6...                          cataract
image93_png.rf.878a3d2beceda73e5ae99eefae404e3b...                          glaucoma
615_right_jpg.rf.879857a7ff0a33eec20050bc6c7b34...  age_related_macular_degeneration
4044_left_jpg.rf.86d47bf869575e941c51311d2c621f...                          diabetes
1492_right_jpg.rf.87ab5ff0292b8502af50bb9050ef0...                          glaucoma

[2282 rows x 1 columns]

## moving  images into their respective folders

In [41]:
df5.loc[filename]

label    hypertension
Name: _7_9739402_jpg.rf.ddd78e6163c1f22b8047a210f7fda96d.jpg, dtype: object

In [42]:
import os
import shutil

# Define the source directory containing all your images
source_directory = 'input'

# Creating the class_ based_structure directory
main_dir = 'class_ based_structure'  # Change this to your desired path
os.makedirs(main_dir, exist_ok=True)

# Define the target directory where you want to create the class-based structure
target_directory = 'class_ based_structure'

# Iterate over the files in the source directory
for root, _, files in os.walk(source_directory):
    for filename in files:
        # Get the class label (e.g., from the filename or a separate metadata file)
        class_label = df5.loc[filename][0]
        # Create a subdirectory for the class if it doesn't exist
        class_directory = os.path.join(target_directory, class_label)
        os.makedirs(class_directory, exist_ok=True)

        # Move the image to the class subdirectory
        source_file = os.path.join(root, filename)
        target_file = os.path.join(class_directory, filename)
        shutil.copy(source_file, target_file)

## Creating train,validate and test folder to store split images

In [43]:
import os

# Specifying the main directory path
main_dir = 'train_validate_test'  # Change this to your desired path

# Creating the main directory
os.makedirs(main_dir, exist_ok=True)

# Specifying the names of the subdirectories
subdirs = ['train', 'validation', 'test']

# Creating the subdirectories inside the main directory
for subdir in subdirs:
    subdir_path = os.path.join(main_dir, subdir)
    os.makedirs(subdir_path, exist_ok=True)

print(f"Directories created: {main_dir} and subdirectories {subdirs}")

Directories created: train_validate_test and subdirectories ['train', 'validation', 'test']

## Converting Images into train, validation and test folder

In [44]:
import os
import shutil
import random

# Define the source directory containing class-based subfolders
source_directory = 'class_ based_structure'

# Define the parent directory where you have created train, validation, and test directories
parent_directory = 'train_validate_test'

# Define the split ratios (e.g., 70% train, 15% validation, 15% test)
train_ratio = 0.6
validation_ratio = 0.20
test_ratio = 0.20

# Iterate over the class-based subdirectories
for class_folder in os.listdir(source_directory):
    class_path = os.path.join(source_directory, class_folder)

    # Create corresponding subdirectories in the parent directory
    train_dir = os.path.join(parent_directory, 'train', class_folder)
    validation_dir = os.path.join(parent_directory, 'validation', class_folder)
    test_dir = os.path.join(parent_directory, 'test', class_folder)

    os.makedirs(train_dir, exist_ok=True)
    os.makedirs(validation_dir, exist_ok=True)
    os.makedirs(test_dir, exist_ok=True)

    # List all image files in the class folder
    image_files = os.listdir(class_path)

    # Shuffle the image files randomly
    random.shuffle(image_files)

    # Determine the number of images for each split
    total_images = len(image_files)
    num_train = int(total_images * train_ratio)
    num_validation = int(total_images * validation_ratio)

    # Distribute the images to train, validation, and test folders
    train_images = image_files[:num_train]
    validation_images = image_files[num_train:num_train + num_validation]
    test_images = image_files[num_train + num_validation:]

    # Move the image files to their respective folders
    for image in train_images:
        src = os.path.join(class_path, image)
        dst = os.path.join(train_dir, image)
        shutil.copy(src, dst)

    for image in validation_images:
        src = os.path.join(class_path, image)
        dst = os.path.join(validation_dir, image)
        shutil.copy(src, dst)

    for image in test_images:
        src = os.path.join(class_path, image)
        dst = os.path.join(test_dir, image)
        shutil.copy(src, dst)